### ISSUE TITLE
cross-fetch throws a "FetchError" but I can't find where "FetchError" is defined

### ISSUE THREAD

**Issue by TimDaub** [lquixada/cross-fetch#139]
E.g. if I wanted to compare with `instanceof` where would I find the "FetchError" that cross-fetch throws when it comes across a non-parsable JSON body and throws upon `await result.json()`.

I've not found anything on Google and MDN related to FetchError so I'm wondering where it stems from. Hopefully not my own code lol.

```
  FetchError {
    message: 'invalid json response body at https://test4.com/ reason: Unexpected token < in JSON at position 0',
    type: 'invalid-json',
  }
```

**Comment by lquixada** [comment]
@TimDaub thanks for taking the time to open this issue. I assume that error is being thrown when running on Node since node-fetch is the lib that implements [FetchError](https://github.com/node-fetch/node-fetch/blob/2.x/src/fetch-error.js#L16). Note that [whatwg-fetch](https://github.com/github/fetch) does not seem to implement it, so it's unlikely the `instanceof` comparison you've mentioned to work in browser environments.
