### ISSUE TITLE
realFetch.call is not a function

### ISSUE THREAD

**Issue by jamespedid** [lquixada/cross-fetch#15]
```
TypeError: realFetch.call is not a function
       at fetch (/usr/lib/leaguegamer/webserver/build/webpack:/datalibrary/node_modules/cross-fetch/dist/node-ponyfill.js:9:1)

```

When I inspect the import using the developer tools, the realFetch is an object, and not a function. On this object, there is the fetch function.

I'm unsure if this is a problem with the library or some kind of weird artifact that I have with the build. It would seem to be the latter, but I can't track it down. Any idea why require('node-fetch') is returning an object?

**Comment by lquixada** [comment]
that's strange. maybe node-fetch is not properly installed on your node_module. go to the /datalibrary/ and run `node -p "require('node-fetch')"`. What's the output?

**Comment by jamespedid** [comment]
I actually figured it out last night. It had to do with the way webpack was building the file. (I use webpack on the server-side too.) It was having trouble loading node-fetch in the right way. I was able to add node-fetch to the list of excludes and it solved the problem.

If anyone else has a problem like this, then this will remain here for troubleshooting.

**Comment by alexvetter** [comment]
Hi @lquixada,
Hi @jamespedid,

I'm currently facing the same issue. I upgraded from `cross-fetch@1.1.1` to `cross-fetch@2.2.0`. After the upgrade I got the runtime error `TypeError: realFetch.call is not a function`. 

I'm using `cross-fetch` in a webpack-bundled TypeScript backend.

If I change the `require` to `require('node-fetch').default` in `./node_modules/cross-fetch/dist/node-ponyfill.js` it works like a charm.  
If I import `node-fetch` instead of `cross-fetch` it also works.

Looks like others have kinda the same problem with `node-fetch` (https://github.com/bitinn/node-fetch/issues/450).

But I'm not sure how to fix this in our code. Perhaps it has something to do with your rollup build?

**Comment by lquixada** [comment]
Hi @alexvetter! I've identified the issue. The newer node-fetch version has two entry-points: main and module. When you require node files (without a bundler), it uses main. When you require bundled file (with target: node), it uses module.

The module entry point uses es modules, thus the "default" property works. I'm already working on a solution.

**Comment by alexvetter** [comment]
Thank you very! I would hoped I could have been of more value for fixing that issue. Really appreciate your fast response!

**Comment by lquixada** [comment]
no problem! btw, can you do `npm install lquixada/cross-fetch` in your project and make sure the patch worked?

**Comment by alexvetter** [comment]
I should have been more clear. Yes, it works! Thanks again. Looking forward to a official release.
